const API = '/api';
const state = { locations: [], routes: [], highlighted: new Set(), selectedIds: new Set(), writesEnabled: true };
const typeColors = {GATE:'#22d3c5',PARKING:'#62dc8a',ADMINISTRATION:'#ffba62',LIBRARY:'#46b9ff',ACADEMIC_BLOCK:'#9d7df5',LABORATORY:'#ff6f91',CAFETERIA:'#ff8b63',HOSTEL:'#ef7fb1',HEALTH_CENTRE:'#ff7185',SPORTS_FACILITY:'#64d8b0',SERVICE_CENTRE:'#a5b8c6',AUDITORIUM:'#d697ff',OTHER:'#a5b8c6'};
const types = [['ACADEMIC_BLOCK','Academic Block'],['ADMINISTRATION','Administration'],['LABORATORY','Laboratory'],['LIBRARY','Library'],['AUDITORIUM','Auditorium'],['HOSTEL','Hostel'],['CAFETERIA','Cafeteria'],['SPORTS_FACILITY','Sports Facility'],['HEALTH_CENTRE','Health Centre'],['PARKING','Parking'],['GATE','Gate'],['SERVICE_CENTRE','Service Centre'],['OTHER','Other']];
const knownPositions = {'GATE-A':[90,280],PARK:[190,350],ADMIN:[250,210],LIB:[410,135],CSE:[490,300],LAB:[650,200],CAFE:[665,390],'HOSTEL-A':[455,470],HEALTH:[790,330],SPORT:[680,490],ARCHIVE:[150,100]};
const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
function esc(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
async function request(path, options={}){const response=await fetch(API+path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let data=null;try{data=await response.json();}catch{}if(!response.ok)throw new Error(data?.error?.message||`Request failed (${response.status})`);return data;}
async function loadData(showNotice=false){try{const [health,locations,routes]=await Promise.all([request('/health'),request('/locations'),request('/routes')]);state.locations=locations;state.routes=routes;state.writesEnabled=health.writesEnabled!==false;$('#apiStatus').textContent=`Connected · Phase ${health.phase}`;$('#syncTime').textContent=state.writesEnabled?`Synced ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`:'Public read-only demo';renderAll();renderAccessMode();if(showNotice)toast('Campus data refreshed');}catch(error){$('#apiStatus').textContent='Disconnected';toast(error.message,true);}}
function renderAccessMode(){for(const notice of $$('[data-readonly]'))notice.hidden=state.writesEnabled;for(const form of [$('#locationForm'),$('#routeForm')]){form.classList.toggle('readonly',!state.writesEnabled);for(const control of form.elements)control.disabled=!state.writesEnabled;}}
function renderAll(){const metres=state.routes.reduce((sum,r)=>sum+r.distanceMetres,0);$('#locationCount').textContent=state.locations.length;$('#routeCount').textContent=state.routes.length;$('#distanceTotal').textContent=metres>=1000?`${(metres/1000).toFixed(1)} km`:`${metres} m`;$('#routeBadge').textContent=`${state.routes.length} routes`;renderMap($('#networkMap'));renderMap($('#plannerMap'));renderPreview();renderLocationTable();renderRouteTable();populateSelects();}
function positions(){const output={};let extra=0;for(const location of state.locations){if(knownPositions[location.id])output[location.id]=knownPositions[location.id];else{const col=extra%4,row=Math.floor(extra/4);output[location.id]=[155+col*170,90+row*120];extra++;}}return output;}
function edgeKey(a,b){return [a,b].sort().join('|');}
function svgEl(name,attrs={}){const el=document.createElementNS('http://www.w3.org/2000/svg',name);for(const [key,value] of Object.entries(attrs))el.setAttribute(key,value);return el;}
function renderMap(svg){svg.replaceChildren();const pos=positions();const defs=svgEl('defs');const glow=svgEl('filter',{id:'glow'});glow.append(svgEl('feGaussianBlur',{stdDeviation:'4',result:'blur'}));defs.append(glow);svg.append(defs);for(const route of state.routes){const a=pos[route.sourceId],b=pos[route.destinationId];if(!a||!b)continue;const highlighted=state.highlighted.has(edgeKey(route.sourceId,route.destinationId));const line=svgEl('line',{x1:a[0],y1:a[1],x2:b[0],y2:b[1],class:`graph-edge${highlighted?' highlight':''}`});svg.append(line);const label=svgEl('text',{x:(a[0]+b[0])/2,y:(a[1]+b[1])/2-7,'text-anchor':'middle',class:`graph-edge-label${highlighted?' highlight':''}`});label.textContent=`${route.distanceMetres}m`;svg.append(label);}for(const location of state.locations){const p=pos[location.id];if(!p)continue;const selected=state.selectedIds.has(location.id);const group=svgEl('g',{class:`graph-node${selected?' selected':''}`,transform:`translate(${p[0]} ${p[1]})`,style:`--node-color:${typeColors[location.type]||typeColors.OTHER}`});group.append(svgEl('circle',{class:'outer',r:'17'}),svgEl('circle',{class:'inner',r:'6'}));const name=svgEl('text',{class:'name',y:'34','text-anchor':'middle'});name.textContent=location.name;const id=svgEl('text',{class:'id',y:'3','text-anchor':'middle'});id.textContent=location.id;const title=svgEl('title');title.textContent=`${location.name} · ${location.typeDisplay}`;group.append(name,id,title);group.addEventListener('click',()=>selectMapNode(location.id));svg.append(group);}}
function selectMapNode(id){const source=$('#sourceSelect'),destination=$('#destinationSelect');if(!source.value||source.value===id){source.value=id;}else{destination.value=id;switchView('planner');}state.selectedIds=new Set([source.value,destination.value].filter(Boolean));renderMap($('#networkMap'));renderMap($('#plannerMap'));}
function renderPreview(){$('#locationPreview').innerHTML=state.locations.slice(0,8).map(l=>`<div class="preview-item"><span class="preview-icon" style="color:${typeColors[l.type]};background:${typeColors[l.type]}18">${esc(l.id.slice(0,2))}</span><span><strong>${esc(l.name)}</strong><small>${esc(l.typeDisplay)}</small></span><small>${esc(l.id)}</small></div>`).join('');}
function renderLocationTable(){const q=$('#locationSearch').value.trim().toLowerCase();const filtered=state.locations.filter(l=>`${l.id} ${l.name} ${l.typeDisplay} ${l.description}`.toLowerCase().includes(q));$('#locationTable').innerHTML=`<div class="table-row header"><span>LOCATION</span><span>TYPE</span><span>DESCRIPTION</span></div>`+(filtered.length?filtered.map(l=>`<div class="table-row"><div class="cell-title"><span class="preview-icon" style="color:${typeColors[l.type]};background:${typeColors[l.type]}18">${esc(l.id.slice(0,2))}</span><span><strong>${esc(l.name)}</strong><small>${esc(l.id)}</small></span></div><span class="type-chip">${esc(l.typeDisplay)}</span><span>${esc(l.description)}</span></div>`).join(''):'<div class="empty-table">No matching locations</div>');}
function nameFor(id){return state.locations.find(l=>l.id===id)?.name||id;}
function renderRouteTable(){$('#routeTable').innerHTML=`<div class="table-row route-row header"><span>SOURCE</span><span></span><span>DESTINATION</span><span>DISTANCE</span></div>`+(state.routes.length?state.routes.map(r=>`<div class="table-row route-row"><div class="cell-title"><span><strong>${esc(nameFor(r.sourceId))}</strong><small>${esc(r.sourceId)}</small></span></div><span>↔</span><div class="cell-title"><span><strong>${esc(nameFor(r.destinationId))}</strong><small>${esc(r.destinationId)}</small></span></div><span class="distance-chip">${r.distanceMetres} m</span></div>`).join(''):'<div class="empty-table">No routes created yet</div>');}
function populateSelects(){const options='<option value="">Select a location</option>'+state.locations.map(l=>`<option value="${esc(l.id)}">${esc(l.name)} (${esc(l.id)})</option>`).join('');for(const select of $$('#sourceSelect,#destinationSelect,#routeSource,#routeDestination')){const old=select.value;select.innerHTML=options;if(state.locations.some(l=>l.id===old))select.value=old;}if(!$('#sourceSelect').value&&state.locations.length)$('#sourceSelect').value=state.locations[0].id;if(!$('#destinationSelect').value&&state.locations.length>1)$('#destinationSelect').value=state.locations[3]?.id||state.locations[1].id;}
function switchView(name){$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}View`));$('#pageTitle').textContent={overview:'Network overview',planner:'Route planner',locations:'Location management',network:'Route network'}[name];window.scrollTo({top:0,behavior:'smooth'});}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=`toast show${error?' error':''}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast',3200);}
async function findRoute(event){event.preventDefault();const source=$('#sourceSelect').value,destination=$('#destinationSelect').value,algorithm=$('input[name="algorithm"]:checked').value;if(source===destination){toast('Choose two different locations',true);return;}const button=event.submitter;button.disabled=true;try{const result=await request(`/routes/${algorithm}?source=${encodeURIComponent(source)}&destination=${encodeURIComponent(destination)}`);state.highlighted=new Set(result.segments.map(s=>edgeKey(s.sourceId,s.destinationId)));state.selectedIds=new Set([source,destination]);$('#algorithmBadge').textContent=result.algorithm;if(!result.found){$('#routeResult').className='route-result empty';$('#routeResult').innerHTML='<span class="result-icon">∅</span><strong>No route exists</strong><p>These locations are disconnected in the current graph.</p>';}else{$('#routeResult').className='route-result success';$('#routeResult').innerHTML=`<div class="route-summary"><span><small>${esc(result.algorithm)} RESULT</small><strong>${result.locations.length} stops</strong></span><b>${result.totalDistanceMetres}<small> m</small></b></div><div class="path-steps">${result.locations.map((l,i)=>`${i?'<i>→</i>':''}<span>${esc(l.name)}</span>`).join('')}</div>`;}renderMap($('#networkMap'));renderMap($('#plannerMap'));}catch(error){toast(error.message,true);}finally{button.disabled=false;}}
async function submitLocation(event){event.preventDefault();const button=event.submitter,form=event.currentTarget,data=Object.fromEntries(new FormData(form));button.disabled=true;try{await request('/locations',{method:'POST',body:JSON.stringify(data)});form.reset();toast('Location saved to PostgreSQL');await loadData();}catch(error){toast(error.message,true);}finally{button.disabled=false;}}
async function submitRoute(event){event.preventDefault();const button=event.submitter,form=event.currentTarget,data=Object.fromEntries(new FormData(form));data.distanceMetres=Number(data.distanceMetres);button.disabled=true;try{await request('/routes',{method:'POST',body:JSON.stringify(data)});form.reset();toast('Route added to the campus graph');await loadData();}catch(error){toast(error.message,true);}finally{button.disabled=false;}}
function init(){for(const [value,label] of types)$('#typeSelect').insertAdjacentHTML('beforeend',`<option value="${value}">${label}</option>`);$$('.nav-item').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$$('[data-goto]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.goto)));$('#refreshBtn').addEventListener('click',()=>loadData(true));$('#locationSearch').addEventListener('input',renderLocationTable);$('#routeSearchForm').addEventListener('submit',findRoute);$('#locationForm').addEventListener('submit',submitLocation);$('#routeForm').addEventListener('submit',submitRoute);$('#swapBtn').addEventListener('click',()=>{const a=$('#sourceSelect'),b=$('#destinationSelect'),v=a.value;a.value=b.value;b.value=v;});$$('input[name="algorithm"]').forEach(r=>r.addEventListener('change',()=>$$('.algorithm-option').forEach(o=>o.classList.toggle('active',o.contains($('input[name="algorithm"]:checked'))))));loadData();}
document.addEventListener('DOMContentLoaded',init);
